# Generated by Django 6.0.4 on 2026-06-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_function", "0002_alter_searchresult_bp_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchresult",
            name="bp_length",
        ),
        migrations.RemoveField(
            model_name="searchresult",
            name="created",
        ),
        migrations.RemoveField(
            model_name="searchresult",
            name="updated",
        ),
    ]
