# Generated by Django 6.0.5 on 2026-07-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_function", "0004_remove_searchresult_ir_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
