# Generated by Django 6.0.4 on 2026-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganelleMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50, unique=True)),
                ('r_rnas_reported', models.IntegerField(blank=True, null=True, verbose_name='rRNAs Reported')),
                ('t_rnas_reported', models.IntegerField(blank=True, null=True, verbose_name='tRNAs Reported')),
                ('gene_count', models.IntegerField(blank=True, null=True, verbose_name='Total Genes Present')),
                ('gc_content', models.FloatField(blank=True, null=True)),
                ('ambiguity_content', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organelle Metadata',
                'verbose_name_plural': 'Organelle Metadata',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50, unique=True)),
                ('taxid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('common_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Common Name')),
                ('superkingdom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Superkingdom')),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kingdom')),
                ('subkingdom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subkingdom')),
                ('phylum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phylum')),
                ('subphylum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subphylum')),
                ('tax_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Class')),
                ('subclass', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subclass')),
                ('order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order')),
                ('suborder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suborder')),
                ('family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Family')),
                ('subfamily', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subfamily')),
                ('tribe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tribe')),
                ('subtribe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtribe')),
                ('genus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Genus')),
                ('subgenus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subgenus')),
                ('species', models.CharField(blank=True, max_length=100, null=True, verbose_name='Species')),
                ('subspecies', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subspecies')),
                ('varietas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Varietas')),
                ('forma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma')),
            ],
            options={
                'verbose_name': 'Taxonomic Information',
                'verbose_name_plural': 'Taxonomic Information',
            },
        ),
    ]
