# Generated by Django 6.0.4 on 2026-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organism_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organellemetadata",
            name="base_pair_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Base Pair Length"
            ),
        ),
        migrations.AddField(
            model_name="organellemetadata",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organellemetadata",
            name="updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Updated"
            ),
        ),
    ]
