# Generated by Django 6.0.4 on 2026-06-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organism_metadata", "0002_organellemetadata_base_pair_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organellemetadata",
            name="organelle_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Organelle Type"
            ),
        ),
    ]
