# Generated by Django 6.0.5 on 2026-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organism_metadata", "0003_organellemetadata_organelle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organellemetadata",
            name="gene_list",
            field=models.JSONField(blank=True, null=True, verbose_name="Gene List"),
        ),
    ]
