# Generated by Django 6.0.4 on 2026-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organism_metadata", "0004_organellemetadata_gene_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organellemetadata",
            name="organelle_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Organelle Type",
            ),
        ),
        migrations.AlterField(
            model_name="organellemetadata",
            name="updated",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Last Updated"
            ),
        ),
    ]
