# Generated by Django 6.0.4 on 2026-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organism_metadata", "0006_organellemetadata_organism_me_gene_li_964402_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organellemetadata",
            name="title",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
