# Generated by Django 6.0.4 on 2026-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organelle_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organellemetadata',
            name='longest_ambiguity_stretch',
            field=models.IntegerField(blank=True, null=True, verbose_name='Longest Ambiguity Stretch (bp)'),
        ),
    ]
