# Generated by Django 6.0.4 on 2026-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organelle_quality", "0002_organellemetadata_longest_ambiguity_stretch"),
    ]

    operations = [
        migrations.AddField(
            model_name="organellemetadata",
            name="duplicate",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=10,
                null=True,
                verbose_name="Self Reported Duplicate?",
            ),
        ),
        migrations.AddField(
            model_name="organellemetadata",
            name="duplicate_accession",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Duplicate Of"
            ),
        ),
    ]
