# Generated by Django 6.0.4 on 2026-08-15 17:35

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    # CONCURRENTLY can't run inside a transaction, and this table is large
    # enough that a plain (locking, transaction-wrapped) GIN build times out
    # against Supabase's pooled connection. Must be run against Postgres via
    # a direct (non-pooled) connection, not the pooled 'supabase' alias used
    # for normal app traffic.
    atomic = False

    dependencies = [
        ("organism_metadata", "0005_alter_organellemetadata_organelle_type_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="SET statement_timeout = '15min';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        AddIndexConcurrently(
            model_name="organellemetadata",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["gene_list"], name="organism_me_gene_li_964402_gin"
            ),
        ),
    ]
