# Generated by Django 6.0.4 on 2026-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_function", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchresult",
            name="bp_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
