# Generated by Django 6.0.4 on 2026-06-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_function", "0003_remove_searchresult_bp_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchresult",
            name="ir_info",
        ),
    ]
