# Generated by Django 6.0.4 on 2026-08-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_function", "0005_delete_searchhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchResult",
        ),
    ]
