# Generated by Django 6.0.4 on 2026-06-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genbank_interaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ir_identification",
            table="plastid_interaction_ir_identification",
        ),
    ]
