# Generated by Django 6.0.4 on 2026-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastid_interaction', '0002_alter_ir_identification_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IR_Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50, unique=True)),
                ('ira_blastinferred', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('ira_blastinferred_start', models.IntegerField(blank=True, null=True, verbose_name='BLAST-inferred Start of IRa (bp)')),
                ('ira_blastinferred_end', models.IntegerField(blank=True, null=True, verbose_name='BLAST-inferred End of IRa (bp)')),
                ('ira_blastinferred_length', models.IntegerField(blank=True, null=True, verbose_name='BLAST-inferred Length of IRa (bp)')),
                ('irb_blastinferred', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('irb_blastinferred_start', models.IntegerField(blank=True, null=True, verbose_name='BLAST-inferred Start of IRb (bp)')),
                ('irb_blastinferred_end', models.IntegerField(blank=True, null=True, verbose_name='BLAST-inferred End of IRb (bp)')),
                ('irb_blastinferred_length', models.IntegerField(blank=True, null=True, verbose_name='BLAST-inferred Length of IRb (bp)')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IR Confirmation',
                'db_table': 'plastid_interaction_ir_confirmation',
            },
        ),
        migrations.AddField(
            model_name='ir_identification',
            name='checked',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Checked'),
        ),
    ]
