# Generated by Django 6.0.4 on 2026-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50, unique=True)),
                ('storage_path', models.CharField(help_text='Path inside the Supabase Storage bucket, e.g. NC_001666.png', max_length=255)),
                ('public_url', models.URLField(help_text='Public URL returned by Supabase Storage', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Last Uploaded')),
            ],
            options={
                'verbose_name': 'Genome Map',
                'verbose_name_plural': 'Genome Maps',
                'ordering': ['accession'],
            },
        ),
    ]
