# Generated by Django 6.0.5 on 2026-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IR_Identification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession", models.CharField(max_length=50, unique=True)),
                ("title", models.TextField(default="No Title")),
                (
                    "updated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Updated"
                    ),
                ),
                (
                    "ir_reported",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            (
                                "exception",
                                "No, or only 1 IR occurs naturally in this species.",
                            ),
                        ],
                        default="no",
                        max_length=50,
                        verbose_name="Inverted Repeats Reported",
                    ),
                ),
                ("ira_reported", models.CharField(max_length=50)),
                (
                    "ira_reported_start",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Start of Inverted Repeat A (bp position)",
                    ),
                ),
                (
                    "ira_reported_end",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="End of Inverted Repeat A (bp position)",
                    ),
                ),
                (
                    "ira_reported_length",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Length of Inverted Repeat A (bp)",
                    ),
                ),
                (
                    "irb_reported",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "irb_reported_start",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Start of Inverted Repeat B (bp position)",
                    ),
                ),
                (
                    "irb_reported_end",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="End of Inverted Repeat B (bp position)",
                    ),
                ),
                (
                    "irb_reported_length",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Length of Inverted Repeat B (bp)",
                    ),
                ),
            ],
            options={
                "verbose_name": "IR Identification",
            },
        ),
    ]
