# Generated by Django 6.0.4 on 2026-06-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plastid_interaction", "0003_ir_confirmation_ir_identification_checked"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IR_Confirmation",
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="ira_blastinferred",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="ira_blastinferred_end",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="BLAST-inferred End of IRa (bp)"
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="ira_blastinferred_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="BLAST-inferred Length of IRa (bp)"
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="ira_blastinferred_start",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="BLAST-inferred Start of IRa (bp)"
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="irb_blastinferred",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="irb_blastinferred_end",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="BLAST-inferred End of IRb (bp)"
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="irb_blastinferred_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="BLAST-inferred Length of IRb (bp)"
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="irb_blastinferred_start",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="BLAST-inferred Start of IRb (bp)"
            ),
        ),
        migrations.AddField(
            model_name="ir_identification",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
